### ISSUE TITLE
Installation of JSHint fails

### ISSUE THREAD

**Issue by melvin-ibuildings** [ibuildingsnl/qa-tools#11]
original created by DRvanR

Well, the title says it all ;)

Output:

```
Do you want to enable JSHint? [Y/n] 
Starting setup of the pre-commit hook for the Ibuildings QA Tools
npm ERR! install Couldn't read dependencies
npm ERR! Error: No 'name' field
npm ERR!     at validName (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:557:40)
npm ERR!     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:340:27)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:140:33
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:270:40
npm ERR!     at [object Object].<anonymous> (fs.js:115:5)
npm ERR!     at [object Object].emit (events.js:64:17)
npm ERR!     at afterRead (fs.js:1117:12)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:292:17
npm ERR!     at Object.wrapper [as oncomplete] (fs.js:254:17)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.5.0-45-generic
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/daan/Workspace/projects/strukton/iworkx/iworkx-blueprint/vendor/ibuildings/qa-tools
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.71
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/daan/Workspace/projects/strukton/iworkx/iworkx-blueprint/vendor/ibuildings/qa-tools/npm-debug.log
npm ERR! not ok code undefined
npm ERR! not ok code 1
PHP Fatal error:  Call to a member function writeln() on a non-object in /home/daan/Workspace/projects/strukton/iworkx/iworkx-blueprint/vendor/ibuildings/qa-tools/src/Ibuildings/QA/Tools/Javascript/Console/InstallJsHintCommand.php on line 59
```

Seems there is a `name` field missing and the error is not handled gracefully since PHP throws a fatal.

**Comment by DRvanR** [comment]
Superseded by https://github.com/ibuildingsnl/qa-tools/issues/69
