### ISSUE TITLE
Allow phpcs inspection in phpstorm for configuration file which is not in project root

### ISSUE THREAD

**Issue by Pton** [ibuildingsnl/qa-tools#133]
Setting up phpcs inspections inside phpstorm and pointing them to phpcs.xml in a location other than the project root (`{projectroot}/config/qa/phpcs.xml` in my case), results in the error below.
```
PHP Code Sniffer
phpcs: PHP Fatal error:  Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Referenced sniff "./vendor/drupal/coder/coder_sniffer/Drupal" does not exist' in C:\www\xxx\vendor\squizlabs\php_codesniffer\CodeSniffer.php:1167
Stack trace:
#0 C:\www\xxx\vendor\squizlabs\php_codesniffer\CodeSniffer.php(780): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), 'C:\\www\\xxx\\c...', 0)
#1 C:\www\xxx\vendor\squizlabs\php_codesniffer\CodeSniffer.php(578): PHP_CodeSniffer->processRuleset('C:\\www\\xxx\\c...')
```

This is caused by the folowing path specified in phpcs.xml: 
```XML
<rule ref="./vendor/drupal/coder/coder_sniffer/Drupal"/>
```

In my case changing this line as follows, fixes the issue:
```XML
<rule ref="./../../vendor/drupal/coder/coder_sniffer/Drupal"/>
````

**Comment by Pton** [comment]
This issue occured using QA Tools 2.x, as it's an outdated version I'll close the ticket.
